- frontend/src/components/NavBar.vue
- frontend/tailwind.js
modify search on navbar component & add small effect at search
> refactor: modify search

- frontend/src/router/index.ts
- frontend/src/views/MainView.vue
- frontend/src/views/SettingView.vue
- frontend/src/views/user/CartView.vue
- frontend/src/views/user/InfoView.vue
- frontend/src/views/user/LikeView.vue
추가한 뷰들 라우터에 추가.
제목에 표시한 각 뷰 추가.
카드 컴포넌트들을 메인에 추가.
> feature: add router, Like, Cart, Info, SettingView / Add Card on Main

- frontend/src/components/DropDown.vue
- frontend/src/config/authConfig.js
- frontend/src/router/index.ts
- frontend/src/service/AuthService.js
예제는 DropDown.vue 에 넣었으니 참고 할 수 있도록...
oidc-client Logout에 대한 지식이 부족해서 꽤나 시간 많이 투자하였다.
이 로그아웃 구현은 accessToken 자체를 revoke를 하는 것은아니다
자체적으로 accessToken을 날린다.
> logout 구성 완료

- frontend/src/router/index.ts
- frontend/src/views/MyInfoView.vue
- frontend/src/views/user/OrderDetailView.vue
- frontend/src/views/user/OrderView.vue
SettingView -> MyInfoView로 이름 변경
그에 맞춰서 라우터 설정 변경.
또 추가로 라우터에 새로운 View추가.
새로운 뷰 : OrderView, OrderDetailView
현 작업 이후로 로직 작업 예정
> Feat:NewView -> Order, OrderDetail / Modify: Setting -> MyInfo (+router)

- frontend/src/views/MainView.vue
- frontend/src/views/MyInfoView.vue
- frontend/src/views/user/CartView.vue
- frontend/src/views/user/InfoView.vue
- frontend/src/views/user/LikeView.vue
- frontend/src/views/user/OrderDetailView.vue
- frontend/src/views/user/OrderView.vue
> Feat: Add Footer

- backend/pom.xml
- backend/src/main/java/com/nextivis/nishopping/domain/repository/UserRepository.java
- backend/src/main/java/com/nextivis/nishopping/service/UserService.java
- backend/src/main/java/com/nextivis/nishopping/service/helper/TimeHelper.java
- backend/src/test/java/com/nextivis/nishopping/domain/repository/UserRepositoryTest.java
- backend/src/test/java/com/nextivis/nishopping/service/UserServiceTest.java
1. issue resolve (Test not Detect)
2. create userService
3. create userService UnitTest
4. userRepository change find Return Type (User => Optional<User>)
> feat : user service

- frontend/src/components/DropDown.vue
- frontend/src/components/NavBar.vue
- frontend/src/views/MyInfoView.vue
MyInfoVeiw에 각 메뉴 이동
NavBar에 홈으로 이동
DropDown에 myinfo로 이동
각 goPage("res:Stinrg")로 주소로 인자로 보내서
$router.push(res)로 해줌.
> Feat: Add $router.push() on Views and Com

- frontend/src/views/MyInfoView.vue
- frontend/src/views/user/CartView.vue
- frontend/src/views/user/InfoView.vue
View의 레이아웃 부분을 완성된 component로 대체
> refactor: insert components into each view

- frontend/src/views/MyInfoView.vue
MyInfoView - AccountCard.vue 사용하지 않는것으로 롤백
> refactor: rollback MyInfoView.vue

- frontend/src/views/user/InfoView.vue
AuthService에서 created()로 데이터를 우선 가져와서 프론트에 뿌려줌.
(-> apiService로 작업하다 잘 안되서 AuthServcie 사용)
여러 데이터를 표시할 수 있게 데이터 출력단 Div들을 추가했으며 v-for 쓸만큼은 아니라 수작업으로함.
수정 버튼을 만들어 수정할때만 input를 v-show로 보여주게 했으며,
input부분들에 데이터를 입력하고 완료를 누르면 처음 create()때 만들어진 데이터들을 수정하게 함.
즉 수정 완료할때 수정된 데이터를 던져주는 apiServce가 있으면 되게 끔 작업했음.
그러나 피드백 요망.
> feat: add new User Data Div, Print Data and fix Data feat.

- backend/src/main/java/com/nextivis/nishopping/domain/entity/Product.java
- backend/src/main/resources/db/migration/V2.0__create_product_table
@dyjung123  테이블 비교 바람
notnull이라 던지 타입 자세히 확인좀 부탁드림
다른게 몇 있는데 나는 이것이 맞다고 판단해서 그렇게 정리를 했는데
어떻게 판단하는지 궁금하구만
> Product create table

- frontend/src/components/Card.vue
- frontend/src/components/DropDown.vue
- frontend/src/components/NavBar.vue
- frontend/src/components/OrderCard.vue
- frontend/src/views/product/DetailProductView.vue
class가 너무 길어지는 것들은 자체 css로 정리함.
> fix: reduction class

- frontend/src/store/index.ts
- frontend/src/types/cart.ts
- frontend/src/types/like.ts
- frontend/src/types/product.ts
- frontend/src/types/state.ts
cartType과 cartTypeArray 정의, 장바구니 관련 actions, mutations 추가
> feat: add cartType & cartTypeArray

- frontend/src/router/index.ts
> refactor: Add Rounter Set for FinalOrderView.vue

- frontend/src/views/product/DetailProductView.vue
DetailProductView에서 apiService 삭제
> hotfix: delete apiService on DetailProductView

- frontend/src/router/index.ts
- frontend/src/views/product/EditProductView.vue
- frontend/tailwind.js
> feat: add EditProductView

- frontend/src/components/CategoryNav.vue
- frontend/tailwind.js
상품 게시판에 좌측에 들어갈 categoryNav component 추가
> feat: add CategoryNav component to be put into product board view

- frontend/src/service/userService.ts
- frontend/src/store/index.ts
- frontend/src/views/user/InfoView.vue
> feat: add default get and 'firstLoginVerify' on userService.ts,

- backend/src/main/java/com/nextivis/nishopping/app/controller/ProductController.java
- backend/src/main/java/com/nextivis/nishopping/app/controller/UserController.java
- backend/src/main/java/com/nextivis/nishopping/domain/entity/Product.java
- backend/src/main/java/com/nextivis/nishopping/domain/repository/ProductRepository.java
- backend/src/main/java/com/nextivis/nishopping/domain/repository/ProductRepository.xml
- backend/src/main/java/com/nextivis/nishopping/domain/service/ProductService.java
- backend/src/main/java/com/nextivis/nishopping/domain/service/helper/RandomHelper.java
- backend/src/main/resources/db/migration/V2.0__create_product_table.sql
- backend/src/test/java/com/nextivis/nishopping/domain/repository/ProductRepositoryTest.java
- backend/src/test/resources/application.yml
> product Service, Controller, Repository

- frontend/src/components/CategoryNav.vue
- frontend/src/views/product/ProductView.vue
CategoryNav component를 ProductView에 삽입
> refactor: insert CategoryNav into ProductView

- frontend/src/components/Loading.vue
> feat: add Loading component
